spring.application.name=cosmos

spring.datasource.url=jdbc:mariadb://1.238.69.48:1029/football
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=iuiu1028
spring.datasource.password=ngr0633!
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect